import SwiftUI
import SwiftData
import UIKit

struct ContentView: View {
    @Environment(\.modelContext) private var context
    @Query(sort: \JobRecord.score, order: .reverse) private var jobs: [JobRecord]
    @Query private var resumes: [ResumeProfile]
    @Query private var preferences: [UserPreferences]
    @State private var selectedTab = 0
    var body: some View { TabView(selection: $selectedTab) { TodayView(jobs: jobs, resume: resumes.first, preferences: preferences.first ?? UserPreferences()).tabItem { Label("今日求职", systemImage: "sparkles") }.tag(0); BoardView(jobs: jobs).tabItem { Label("求职看板", systemImage: "rectangle.grid.2x2") }.tag(1); ResumeView().tabItem { Label("简历", systemImage: "doc.text") }.tag(2); SettingsView().tabItem { Label("设置", systemImage: "gearshape") }.tag(3) }.tint(.indigo).task { if preferences.isEmpty { context.insert(UserPreferences()); try? context.save() } } }
}

struct TodayView: View { let jobs: [JobRecord]; let resume: ResumeProfile?; let preferences: UserPreferences; var body: some View { NavigationStack { List { Section { HStack { VStack(alignment: .leading) { Text("今日求职").font(.largeTitle.bold()); Text("已处理 3 / \(preferences.dailyLimit)").foregroundStyle(.secondary) }; Spacer(); Button("导入职位") {}.buttonStyle(.borderedProminent) } }.listRowBackground(Color.clear); Section("AI 优先推荐") { ForEach(jobs.filter { $0.score >= 75 }.prefix(5)) { job in NavigationLink { JobDetailView(job: job, resume: resume) } label: { JobRow(job: job) } } }; Section("待跟进") { Text("2 位招聘者等待回复").foregroundStyle(.secondary) } } .navigationTitle("").listStyle(.insetGrouped) } } }
struct JobRow: View { let job: JobRecord; var body: some View { HStack { VStack(alignment: .leading, spacing: 4) { Text("\(job.score) 分").font(.headline).foregroundStyle(job.score >= 75 ? .green : .orange); Text("\(job.title) · \(job.city)").font(.subheadline); Text(job.reasons.prefix(2).joined(separator: " · ")).font(.caption).foregroundStyle(.secondary) }; Spacer(); Image(systemName: "chevron.right").foregroundStyle(.tertiary) } } }
struct JobDetailView: View { let job: JobRecord; let resume: ResumeProfile?; @State private var tone: OpeningTone = .professional; @State private var copied = false; var body: some View { let analyzer = JobAnalyzer(); ScrollView { VStack(alignment: .leading, spacing: 18) { Text(job.title).font(.title.bold()); Text("\(job.company) · \(job.city) · \(job.salary)").foregroundStyle(.secondary); Text("匹配度 \(job.score) 分").font(.title2.bold()).foregroundStyle(.green); if !job.risks.isEmpty { Label(job.risks.joined(separator: "、"), systemImage: "exclamationmark.triangle").foregroundStyle(.orange) }; Text("推荐理由").font(.headline); ForEach(job.reasons, id: \.self) { Text("• \($0)") }; Text("开场白").font(.headline); Picker("语气", selection: $tone) { ForEach(OpeningTone.allCases, id: \.self) { Text($0.rawValue).tag($0) } }.pickerStyle(.segmented); Text(analyzer.opening(role: job.title, company: job.company, resume: resume, tone: tone)).padding().background(.indigo.opacity(0.08)).clipShape(RoundedRectangle(cornerRadius: 12)); Button(copied ? "已复制，打开 BOSS" : "复制并打开 BOSS") { UIPasteboard.general.string = analyzer.opening(role: job.title, company: job.company, resume: resume, tone: tone); copied = true; if let url = URL(string: "bosszp://") { UIApplication.shared.open(url) } else { UIApplication.shared.open(URL(string: "https://www.zhipin.com")!) } }.buttonStyle(.borderedProminent) }.padding() } .navigationTitle("职位分析") } }
struct BoardView: View { let jobs: [JobRecord]; var body: some View { NavigationStack { List { ForEach(JobStage.allCases, id: \.self) { stage in Section(stage.rawValue) { ForEach(jobs.filter { $0.stage == stage }) { JobRow(job: $0) } } } }.navigationTitle("求职看板") } } }
struct ResumeView: View { var body: some View { NavigationStack { ContentUnavailableView("简历中心", systemImage: "doc.text", description: Text("请从“文件”App 导入 PDF、DOCX 或 TXT 简历")) .navigationTitle("简历") } } }
struct SettingsView: View { @State private var faceID = true; @State private var ai = false; var body: some View { NavigationStack { Form { Section("AI") { Toggle("启用云端 AI 增强", isOn: $ai); Text("关闭时仍可使用本地规则和预设文案").font(.caption).foregroundStyle(.secondary) }; Section("隐私") { Toggle("Face ID 解锁", isOn: $faceID); Text("不保存 BOSS 密码、Cookie 或验证码").font(.caption).foregroundStyle(.secondary) }; Section("提醒") { Text("每日 10:00 推荐 · 48 小时跟进 · 面试前 24/2 小时") } }.navigationTitle("设置") } } }
