const KEY='job-assistant-v2';
const degreeRank={"":0,"大专":1,"本科":2,"硕士":3,"博士":4};
const defaults={targetRole:'',city:'',degree:'本科',years:'',minSalary:'',currentSalary:'',skills:'',industry:'',blacklist:'外包,人力派遣,保险,理财,大小周,单休,销售',dailyLimit:20};
const state=JSON.parse(localStorage.getItem(KEY)||'null')||{prefs:defaults,jobs:[],today:{date:'',count:0},filter:'all'};
const $=s=>document.querySelector(s);
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){localStorage.setItem(KEY,JSON.stringify(state));}
function toast(message){const node=$('#toast');node.textContent=message;node.classList.add('show');setTimeout(()=>node.classList.remove('show'),2200);}
function today(){const d=new Date().toISOString().slice(0,10);if(state.today.date!==d)state.today={date:d,count:0};}
function tokens(value){return String(value||'').toLowerCase().split(/[，,、\s/|；;]+/).map(x=>x.trim()).filter(x=>x.length>1);}
function textFirst(regex,text){const m=String(text||'').match(regex);return m?m[1].trim():'';}
function numberFirst(regex,text){const m=String(text||'').match(regex);return m?Number(m[1]):0;}
function parseJob(raw,url,fields){const text=String(raw||'').trim();const title=fields.title||textFirst(/(?:职位|岗位|招聘)\s*[:：]?\s*([^\n|｜]{2,40})/i,text)||text.split(/\r?\n/).map(s=>s.trim()).find(s=>s.length>2&&s.length<35)||'待确认职位';const company=fields.company||textFirst(/(?:公司|企业)\s*[:：]?\s*([^\n|｜]{2,35})/i,text)||'待确认公司';const city=fields.city||textFirst(/(?:城市|地点|工作地点)\s*[:：]?\s*([^\n|｜]{2,20})/i,text)||'待确认';const maxSalary=Number(fields.salary)||numberFirst(/\d+(?:\.\d+)?\s*[-~至]\s*(\d+(?:\.\d+)?)\s*[kK]/,text)||numberFirst(/(\d+(?:\.\d+)?)\s*[kK]\s*\/?.{0,4}(?:月|个月)/,text);const minSalary=numberFirst(/(\d+(?:\.\d+)?)\s*[-~至]\s*\d+(?:\.\d+)?\s*[kK]/,text)||maxSalary;const years=Number(fields.years)||numberFirst(/(?:经验|工作年限).{0,8}?(\d+)\s*年/,text);const degree=fields.degree||(['博士','硕士','本科','大专'].find(x=>text.includes(x))||'');return {id:Date.now(),title,company,city,maxSalary,minSalary,years,degree,industry:fields.industry||'',url,text,createdAt:new Date().toISOString()};}
function scoreJob(job){const p=state.prefs;const corpus=`${job.title} ${job.company} ${job.city} ${job.industry} ${job.text}`.toLowerCase();const blocked=tokens(p.blacklist).filter(x=>corpus.includes(x));const hard=[];if(Number(p.minSalary)&&job.minSalary&&job.minSalary<Number(p.minSalary)*.8)hard.push('最低薪资低于期望下限的 80%');if(blocked.length)hard.push(`命中排除词：${blocked.join('、')}`);if(job.degree&&degreeRank[job.degree]>degreeRank[p.degree||'本科'])hard.push(`学历要求 ${job.degree} 高于你的 ${p.degree||'本科'}`);const target=tokens(p.targetRole);const unrelated=['销售','C++','客服','保险经纪','房产'].filter(x=>corpus.includes(x)&&!target.some(t=>x.toLowerCase().includes(t)||t.includes(x.toLowerCase())));if(target.length&&unrelated.length&&target.every(t=>!corpus.includes(t)))hard.push(`职位与目标岗位可能不相关：${unrelated[0]}`);const skills=tokens(p.skills);const jobSkills=[...new Set(['java','python','spring','spring boot','mysql','redis','kafka','微服务','高并发','tensorflow','sql','swift','产品','增长','数据'].filter(x=>corpus.includes(x)))];const matched=jobSkills.filter(s=>skills.some(x=>x.includes(s)||s.includes(x)));const skillScore=jobSkills.length?matched.length/jobSkills.length*100:(target.some(t=>corpus.includes(t))?70:45);const expDiff=Math.abs(Number(p.years||0)-Number(job.years||0));const expScore=!job.years||!p.years?70:expDiff<=1?100:Math.max(0,100-expDiff*24);const industryScore=!p.industry||!job.industry?65:tokens(p.industry).some(x=>job.industry.toLowerCase().includes(x)||corpus.includes(x))?100:45;const salaryScore=!p.currentSalary||!job.maxSalary?65:job.maxSalary>=Number(p.currentSalary)*1.1?100:10;const score=Math.round(skillScore*.5+expScore*.2+industryScore*.2+salaryScore*.1);let action=hard.length?'skip':score>=85?'priority':score>=60?'watch':'skip';return {...job,score,action,hard,matched,jobSkills,reason:hard.length?hard.join('；'):`技能匹配 ${matched.length}/${jobSkills.length||'未识别'}；经验匹配 ${Math.round(expScore)} 分；行业匹配 ${Math.round(industryScore)} 分。`,gap:jobSkills.filter(s=>!matched.includes(s)),message:`你好，我关注到贵司的${job.title}岗位。我的经历与岗位要求有较高关联，尤其是${matched.slice(0,2).join('、')||'相关项目经验'}。希望有机会进一步了解团队的业务目标和岗位重点，方便沟通一下吗？`};}
function openView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.go===id));window.scrollTo({top:0,behavior:'smooth'});if(id==='jobsView')renderJobs();}
function card(job){const actionLabel={priority:'优先沟通',watch:'观望收藏',skip:'跳过'}[job.action];const extra=job.action==='priority'?`<button data-copy="${job.id}">复制开场白</button><button data-open="${job.id}">去 BOSS</button>`:job.action==='watch'?`<button data-favorite="${job.id}">收藏 / 待提升</button>`:`<button data-delete="${job.id}">删除记录</button>`;return `<article class="job-card"><div class="job-top"><div><h3>${esc(job.title)}</h3><p>${esc(job.company)} · ${esc(job.city)}${job.maxSalary?` · ${job.maxSalary}K/月`:''}</p></div><span class="score ${job.action}">${job.score} 分</span></div><div class="tags"><span>${actionLabel}</span>${job.gap.slice(0,2).map(x=>`<span>缺 ${esc(x)}</span>`).join('')}</div><p>${esc(job.reason)}</p><div class="job-actions">${extra}</div></article>`;}
function renderHome(){today();const priority=state.jobs.filter(j=>j.action==='priority');$('#todayLabel').textContent=`今日建议沟通 ${state.today.count} / ${Number(state.prefs.dailyLimit)||20}`;$('#priorityCount').textContent=priority.length;$('#watchCount').textContent=state.jobs.filter(j=>j.action==='watch').length;$('#savedCount').textContent=state.jobs.length;$('#priorityList').innerHTML=priority.length?priority.slice(0,3).map(card).join(''):'<p class="empty">还没有优先职位。先导入一个 BOSS 职位吧。</p>';bindJobActions();}
function renderJobs(){const filtered=state.filter==='all'?state.jobs:state.jobs.filter(j=>j.action===state.filter);$('#jobList').innerHTML=filtered.length?filtered.map(card).join(''):'<p class="empty">这里还没有职位记录。</p>';document.querySelectorAll('#filters .pill').forEach(b=>b.classList.toggle('active',b.dataset.filter===state.filter));bindJobActions();}
function bindJobActions(){document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{const j=state.jobs.find(x=>x.id===Number(b.dataset.copy));try{await navigator.clipboard.writeText(j.message);toast('开场白已复制，请在 BOSS 内确认发送');}catch{toast('请长按复制开场白');}});document.querySelectorAll('[data-open]').forEach(b=>b.onclick=async()=>{const j=state.jobs.find(x=>x.id===Number(b.dataset.open));today();if(state.today.count>=Number(state.prefs.dailyLimit||20))return toast('今日建议沟通已达上限');try{await navigator.clipboard.writeText(j.message);}catch{}state.today.count++;save();renderHome();if(j.url)window.open(j.url,'_blank');else toast('已复制文案，请手动打开 BOSS 找到此职位');});document.querySelectorAll('[data-favorite]').forEach(b=>b.onclick=()=>toast('已标记为待提升，可补足短板后再沟通'));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{state.jobs=state.jobs.filter(j=>j.id!==Number(b.dataset.delete));save();renderJobs();renderHome();});}
document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>openView(b.dataset.go)));
$('#profileForm').addEventListener('submit',e=>{e.preventDefault();state.prefs={...defaults,...Object.fromEntries(new FormData(e.currentTarget))};save();toast('求职偏好已保存');renderHome();openView('homeView');});
Object.entries(state.prefs).forEach(([k,v])=>{const node=$(`#profileForm [name="${k}"]`);if(node)node.value=v;});
$('#jobForm').addEventListener('submit',e=>{e.preventDefault();const fields={title:$('#jobTitle').value.trim(),company:$('#jobCompany').value.trim(),city:$('#jobCity').value.trim(),salary:$('#jobSalary').value,years:$('#jobYears').value,degree:$('#jobDegree').value,industry:$('#jobIndustry').value.trim()};const raw=$('#jobText').value.trim(),url=$('#jobUrl').value.trim();if(!raw&&!url)return toast('请粘贴职位链接或职位文本');const analyzed=scoreJob(parseJob(raw||url,url,fields));state.jobs.unshift(analyzed);save();const r=$('#analysisResult');r.hidden=false;r.innerHTML=`<h3>${analyzed.hard.length?'已跳过：':'分析完成：'}${analyzed.score} 分</h3><p><strong>${esc(analyzed.title)}</strong> · ${esc(analyzed.company)}</p><p>${esc(analyzed.reason)}</p>${analyzed.gap.length?`<p>待提升：${esc(analyzed.gap.join('、'))}</p>`:''}<p><strong>策略：</strong>${analyzed.action==='priority'?'加入优先沟通队列，已生成开场白。':analyzed.action==='watch'?'建议收藏，补足短板后再沟通。':'不建议继续处理。'}</p>${analyzed.action==='priority'?'<button class="button primary" id="resultCopy">复制开场白</button>':''}`;if(analyzed.action==='priority')$('#resultCopy').onclick=async()=>{try{await navigator.clipboard.writeText(analyzed.message);toast('开场白已复制');}catch{toast('请手动复制开场白');}};renderHome();});
$('#pasteButton').onclick=async()=>{try{$('#jobText').value=await navigator.clipboard.readText();toast('已粘贴');}catch{toast('请长按文本框后选择粘贴');}};
$('#filters').onclick=e=>{if(!e.target.dataset.filter)return;state.filter=e.target.dataset.filter;renderJobs();};
$('#clearJobs').onclick=()=>{if(confirm('确定清空本机保存的全部职位吗？')){state.jobs=[];save();renderJobs();renderHome();}};
$('#installHelp').onclick=()=>$('#helpDialog').showModal();$('.dialog-close').onclick=()=>$('#helpDialog').close();
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
renderHome();

// One-click import from the companion Chrome/Edge extension. The extension only
// supplies text after the user explicitly clicks its "import" button.
(() => {
  const encoded = new URLSearchParams(location.search).get('import');
  if (!encoded) return;
  try {
    const bytes = Uint8Array.from(atob(encoded), char => char.charCodeAt(0));
    const payload = JSON.parse(new TextDecoder().decode(bytes));
    if (!payload || typeof payload.text !== 'string' || !payload.text.trim()) throw new Error('empty import');
    $('#jobUrl').value = String(payload.url || '');
    $('#jobText').value = payload.text.slice(0, 2500);
    $('#jobTitle').value = String(payload.title || '');
    history.replaceState({}, document.title, location.pathname);
    openView('importView');
    $('#jobForm').requestSubmit();
    toast('已从浏览器当前页面导入并分析');
  } catch {
    history.replaceState({}, document.title, location.pathname);
    toast('页面导入失败，请在导入页手动粘贴职位文本');
  }
})();
